name: Build & lint

on:
  push:
  pull_request:

jobs:
  build-api:
    name: API
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
          npx eslint common func-*

  build-frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
          npx eslint src
