name: Build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:

jobs:
  build-and-lint:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build frontend
        run: |
          cd frontend
          npm run build
          npx eslint src

      - name: Build API
        run: |
          cd api
          npm run build
          npx eslint common func-*
