name: Deployment

on:
  push:
    branches:
      - main

# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build API
        working-directory: api
        run: |
          npm ci
          npm run build
          npx eslint common func-*

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build
          npx eslint src

      - name: Build and deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "./frontend"
          output_location: build
          api_location: "./api"
